name: interactive_slider
description: A Cupertino-themed interactive continuous slider widget that is inspired by the slider widgets used in Apple Music.
version: 0.5.1
repository: https://github.com/jonas-zebari/interactive_slider

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
